[package]
name = "rlua_serde"
version = "0.5.0"
authors = ["Quinten Kock <quintenkock@gmail.com>", "zrkn <zrkn@email.su>"]
description = "Serde (De)serializer implementation for rlua Value"
repository = "https://github.com/zrkn/rlua_serde/"
readme = "README.md"
keywords = ["lua", "serde"]
license = "MIT"

[dependencies]
rlua  = { version = "0.19", default-features = false}
serde = "1.0"

[dev-dependencies]
serde_bytes = "0.11.9"
serde_derive = "1.0"
serde_json = "1.0"

[features]
arrays = []
